export const ADDRESSES = [
    { label: "Toshkent sh., Yunusobod tumani, Shahrisabz ko‘chasi, 7-uy (100000)", value: "Toshkent sh., Yunusobod tumani, Shahrisabz ko‘chasi, 7-uy. Mo‘ljal: Oloy bozori" },
    { label: "Toshkent sh., Mirzo Ulug‘bek tumani, Mo‘minov ko‘chasi, 4/1-uy (100001)", value: "Toshkent sh., Mirzo Ulug‘bek tumani, Mo‘minov ko‘chasi, 4/1-uy. Mo‘ljal: IT PARK" },
    { label: "Toshkent sh., Mirzo Ulug‘bek tumani, Parkent ko‘chasi, 74-uy (100007)", value: "Toshkent sh., Mirzo Ulug‘bek tumani, Parkent ko‘chasi, 74-uy. Mo‘ljal: Parkent bozori" },
    { label: "Toshkent sh., Shayxontohur tumani, Navoiy ko‘chasi, 26-uy (100011)", value: "Toshkent sh., Shayxontohur tumani, Navoiy ko‘chasi, 26-uy. Mo‘ljal: Tashkent City" },
    { label: "Toshkent sh., Sergeli tumani, Sergeli-2 dahasi (100012)", value: "Toshkent sh., Sergeli tumani, Sergeli-2 dahasi. Mo‘ljal: Korzinka Sergeli" },
    { label: "Toshkent sh., Olmazor tumani, G‘afur G‘ulom ko‘chasi, 2-uy (100019)", value: "Toshkent sh., Olmazor tumani, G‘afur G‘ulom ko‘chasi, 2-uy. Mo‘ljal: Ganga" },
    { label: "Toshkent sh., Shayxontohur tumani, Bog‘ ko‘chasi, 4-uy (100020)", value: "Toshkent sh., Shayxontohur tumani, Bog‘ ko‘chasi, 4-uy. Mo‘ljal: Metro Tinchlik" },
    { label: "Toshkent sh., Mirobod tumani, Nukus ko‘chasi, 2-uy (100060)", value: "Toshkent sh., Mirobod tumani, Nukus ko‘chasi, 2-uy. Mo‘ljal: Shimoliy vokzal" },
    { label: "Toshkent sh., Chilonzor tumani, Furqat ko‘chasi, 167-uy (100066)", value: "Toshkent sh., Chilonzor tumani, Furqat ko‘chasi, 167-uy. Mo‘ljal: Magic City" },
    { label: "Toshkent sh., Olmazor tumani, Qoraqamish 1/1, 23-dom (100069)", value: "Toshkent sh., Olmazor tumani, Qoraqamish 1/1, 23-dom. Mo‘ljal: Olmazor prokuraturasi" },
    { label: "Toshkent sh., Yunusobod tumani, A.Temur ko‘chasi, 98-uy (100084)", value: "Toshkent sh., Yunusobod tumani, A.Temur ko‘chasi, 98-uy. Mo‘ljal: NBU bosh ofisi" },
    { label: "Toshkent sh., Uchtepa tumani, O‘rikzor, 32-uy (100210)", value: "Toshkent sh., Uchtepa tumani, O‘rikzor, 32-uy. Mo‘ljal: O‘rikzor mahallasi" },
    { label: "Toshkent vil., Olmaliq sh., Ehtirom ko‘chasi, 8-uy (110100)", value: "Toshkent vil., Olmaliq sh., Ehtirom ko‘chasi, 8-uy. Mo‘ljal: Uztelekom" },
    { label: "Toshkent vil., Angren sh., Istiqlol ko‘chasi, 3-uy (110200)", value: "Toshkent vil., Angren sh., Istiqlol ko‘chasi, 3-uy. Mo‘ljal: Angren hokimligi" },
    { label: "Toshkent vil., Ohangaron sh., Ezgulik ko‘chasi, 98-uy (110300)", value: "Toshkent vil., Ohangaron sh., Ezgulik ko‘chasi, 98-uy. Mo‘ljal: Dehqon bozori" },
    { label: "Toshkent vil., Bekobod sh., Hojimurodova ko‘chasi, 18A-uy (110500)", value: "Toshkent vil., Bekobod sh., Hojimurodova ko‘chasi, 18A-uy. Mo‘ljal: Markaziy pochta" },
    { label: "Toshkent vil., Chirchiq sh., P.Yusupov ko‘chasi, 5-uy (111700)", value: "Toshkent vil., Chirchiq sh., P.Yusupov ko‘chasi, 5-uy. Mo‘ljal: O‘zbegim to‘yxonasi" },
    { label: "Andijon vil., Andijon sh., Cholponshoh ko‘chasi, 26-uy (170104)", value: "Andijon vil., Andijon sh., Cholponshoh ko‘chasi, 26-uy. Mo‘ljal: Al-Mansur gilam yuvish" },
    { label: "Andijon vil., Andijon sh., 1-kichik daxa, 21-uy (170100)", value: "Andijon vil., Andijon sh., 1-kichik daxa, 21-uy. Mo‘ljal: Delfin suzish havzasi" },
    { label: "Andijon vil., Asaka tumani, Sohil bo‘yi ko‘chasi, 6-uy (170200)", value: "Andijon vil., Asaka tumani, Sohil bo‘yi ko‘chasi, 6-uy. Mo‘ljal: Soy bo‘yi" },
    { label: "Andijon vil., Shahrixon tumani, Shahrixon shox ko‘chasi (171600)", value: "Andijon vil., Shahrixon tumani, Shahrixon shox ko‘chasi. Mo‘ljal: Avtoshoxbekat yonida" },
    { label: "Farg‘ona vil., Farg‘ona sh., Alisher Navoiy ko‘chasi, 21-uy (150100)", value: "Farg‘ona vil., Farg‘ona sh., Alisher Navoiy ko‘chasi, 21-uy. Mo‘ljal: Viloyat hokimligi" },
    { label: "Farg‘ona vil., Qo‘qon sh., Istiqlol ko‘chasi, 45-uy (150700)", value: "Farg‘ona vil., Qo‘qon sh., Istiqlol ko‘chasi, 45-uy. Mo‘ljal: Qo‘qon universiteti" },
    { label: "Farg‘ona vil., Marg‘ilon sh., Mustaqillik ko‘chasi, 12-uy (151100)", value: "Farg‘ona vil., Marg‘ilon sh., Mustaqillik ko‘chasi, 12-uy. Mo‘ljal: Marg‘ilon bozori" },
    { label: "Namangan vil., Namangan sh., Nodira ko‘chasi, 5-uy (160100)", value: "Namangan vil., Namangan sh., Nodira ko‘chasi, 5-uy. Mo‘ljal: Namangan markaziy pochtasi" },
    { label: "Namangan vil., Chust tumani, Mustaqillik ko‘chasi, 1-uy (160500)", value: "Namangan vil., Chust tumani, Mustaqillik ko‘chasi, 1-uy. Mo‘ljal: Chust pichoqlari markazi" },
    { label: "Samarqand vil., Samarqand sh., Pochta ko‘chasi, 1-uy (140100)", value: "Samarqand vil., Samarqand sh., Pochta ko‘chasi, 1-uy. Mo‘ljal: Registon yaqinida" },
    { label: "Samarqand vil., Kattaqo‘rg‘on sh., Amir Temur ko‘chasi, 24-uy (140200)", value: "Samarqand vil., Kattaqo‘rg‘on sh., Amir Temur ko‘chasi, 24-uy. Mo‘ljal: Shahar markazi" },
    { label: "Buxoro vil., Buxoro sh., M.Iqbol ko‘chasi, 2-uy (200100)", value: "Buxoro vil., Buxoro sh., M.Iqbol ko‘chasi, 2-uy. Mo‘ljal: Buxoro markaziy bozori" },
    { label: "Buxoro vil., G‘ijduvon tumani, Yusuf Hamadoniy ko‘chasi, 5-uy (200300)", value: "Buxoro vil., G‘ijduvon tumani, Yusuf Hamadoniy ko‘chasi, 5-uy. Mo‘ljal: G‘ijduvon kabobxonasi" },
    { label: "Navoiy vil., Navoiy sh., Islom Karimov ko‘chasi, 10-uy (210100)", value: "Navoiy vil., Navoiy sh., Islom Karimov ko‘chasi, 10-uy. Mo‘ljal: Navoiy shahar hokimligi" },
    { label: "Qashqadaryo vil., Qarshi sh., Mustaqillik ko‘chasi, 4-uy (180100)", value: "Qashqadaryo vil., Qarshi sh., Mustaqillik ko‘chasi, 4-uy. Mo‘ljal: Qarshi vokzali" },
    { label: "Qashqadaryo vil., Shahrisabz sh., Ipak yo‘li ko‘chasi, 3-uy (181300)", value: "Qashqadaryo vil., Shahrisabz sh., Ipak yo‘li ko‘chasi, 3-uy. Mo‘ljal: Oqsaroy" },
    { label: "Surxondaryo vil., Termiz sh., At-Termiziy ko‘chasi, 1-uy (190100)", value: "Surxondaryo vil., Termiz sh., At-Termiziy ko‘chasi, 1-uy. Mo‘ljal: Markaziy masjid" },
    { label: "Xorazm vil., Urganch sh., Al-Xorazmiy ko‘chasi, 12-uy (220100)", value: "Xorazm vil., Urganch sh., Al-Xorazmiy ko‘chasi, 12-uy. Mo‘ljal: Urganch dehqon bozori" },
    { label: "Xorazm vil., Xiva sh., Najmiddin Kubro ko‘chasi, 5-uy (220900)", value: "Xorazm vil., Xiva sh., Najmiddin Kubro ko‘chasi, 5-uy. Mo‘ljal: Ichan Qala" },
    { label: "Jizzax vil., Jizzax sh., Sh.Rashidov ko‘chasi, 15-uy (130100)", value: "Jizzax vil., Jizzax sh., Sh.Rashidov ko‘chasi, 15-uy. Mo‘ljal: Jizzax viloyat pochtasi" },
    { label: "Sirdaryo vil., Guliston sh., O‘zbekiston ko‘chasi, 2-uy (120100)", value: "Sirdaryo vil., Guliston sh., O‘zbekiston ko‘chasi, 2-uy. Mo‘ljal: Guliston shahar hokimligi" },
    { label: "Qoraqalpog‘iston Resp., Nukus sh., Ernazar Olako‘z ko‘chasi, 1-uy (230100)", value: "Qoraqalpog‘iston Resp., Nukus sh., Ernazar Olako‘z ko‘chasi, 1-uy. Mo‘ljal: Savitskiy muzeyi" }
];
